use_frameworks!

platform :ios, '9.0'

target 'XEmptyDataSet_Example' do
  pod 'XEmptyDataSet', :path => '../'

  target 'XEmptyDataSet_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
